# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Mid defence\.git-rewrite\t\OpenCv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(794, 585)
        self.start_button_1 = QtWidgets.QPushButton(Dialog)
        self.start_button_1.setGeometry(QtCore.QRect(40, 370, 221, 31))
        self.start_button_1.setObjectName("start_button_1")
        self.camera_display = QtWidgets.QLabel(Dialog)
        self.camera_display.setGeometry(QtCore.QRect(40, 50, 421, 281))
        self.camera_display.setFrameShape(QtWidgets.QFrame.Box)
        self.camera_display.setText("")
        self.camera_display.setObjectName("camera_display")
        self.threshhold_display = QtWidgets.QLabel(Dialog)
        self.threshhold_display.setGeometry(QtCore.QRect(510, 50, 271, 231))
        self.threshhold_display.setFrameShape(QtWidgets.QFrame.Box)
        self.threshhold_display.setText("")
        self.threshhold_display.setObjectName("threshhold_display")
        self.adjust_button_1 = QtWidgets.QPushButton(Dialog)
        self.adjust_button_1.setGeometry(QtCore.QRect(40, 410, 221, 31))
        self.adjust_button_1.setObjectName("adjust_button_1")
        self.save_button_1 = QtWidgets.QPushButton(Dialog)
        self.save_button_1.setGeometry(QtCore.QRect(40, 450, 221, 31))
        self.save_button_1.setObjectName("save_button_1")
        self.color2_value = QtWidgets.QLabel(Dialog)
        self.color2_value.setGeometry(QtCore.QRect(40, 340, 361, 25))
        self.color2_value.setObjectName("color2_value")
        self.toggle_display = QtWidgets.QLabel(Dialog)
        self.toggle_display.setGeometry(QtCore.QRect(510, 350, 271, 211))
        self.toggle_display.setFrameShape(QtWidgets.QFrame.Box)
        self.toggle_display.setText("")
        self.toggle_display.setObjectName("toggle_display")
        self.camera_here_text = QtWidgets.QLabel(Dialog)
        self.camera_here_text.setGeometry(QtCore.QRect(40, 20, 361, 25))
        self.camera_here_text.setObjectName("camera_here_text")
        self.Threshold_here_text = QtWidgets.QLabel(Dialog)
        self.Threshold_here_text.setGeometry(QtCore.QRect(510, 20, 361, 25))
        self.Threshold_here_text.setObjectName("Threshold_here_text")
        self.toggle_text = QtWidgets.QLabel(Dialog)
        self.toggle_text.setGeometry(QtCore.QRect(510, 330, 361, 25))
        self.toggle_text.setObjectName("toggle_text")
        self.start_button_1.raise_()
        self.adjust_button_1.raise_()
        self.threshhold_display.raise_()
        self.camera_display.raise_()
        self.save_button_1.raise_()
        self.color2_value.raise_()
        self.toggle_display.raise_()
        self.camera_here_text.raise_()
        self.Threshold_here_text.raise_()
        self.toggle_text.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start_button_1.setText(_translate("Dialog", "1. Start Webcam"))
        self.adjust_button_1.setText(_translate("Dialog", "2. Adjust Threshold"))
        self.save_button_1.setText(_translate("Dialog", "3. Save Histogram"))
        self.color2_value.setText(_translate("Dialog", "Setup the Histogram."))
        self.camera_here_text.setText(_translate("Dialog", "Camera Here:"))
        self.Threshold_here_text.setText(_translate("Dialog", "Threshold Here:"))
        self.toggle_text.setText(_translate("Dialog", "Final Histogram Here:"))
