# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Mid defence\.git-rewrite\t\OpenCv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(794, 585)
        self.start_button = QtWidgets.QPushButton(Dialog)
        self.start_button.setGeometry(QtCore.QRect(20, 430, 221, 31))
        self.start_button.setObjectName("start_button")
        self.camera_display = QtWidgets.QLabel(Dialog)
        self.camera_display.setGeometry(QtCore.QRect(20, 110, 421, 281))
        self.camera_display.setFrameShape(QtWidgets.QFrame.Box)
        self.camera_display.setText("")
        self.camera_display.setObjectName("camera_display")
        self.threshhold_display = QtWidgets.QLabel(Dialog)
        self.threshhold_display.setGeometry(QtCore.QRect(490, 110, 271, 231))
        self.threshhold_display.setFrameShape(QtWidgets.QFrame.Box)
        self.threshhold_display.setText("")
        self.threshhold_display.setObjectName("threshhold_display")
        self.stop_button = QtWidgets.QPushButton(Dialog)
        self.stop_button.setGeometry(QtCore.QRect(20, 470, 221, 31))
        self.stop_button.setObjectName("stop_button")
        self.color2_value = QtWidgets.QLabel(Dialog)
        self.color2_value.setGeometry(QtCore.QRect(20, 400, 361, 25))
        self.color2_value.setObjectName("color2_value")
        self.text = QtWidgets.QLabel(Dialog)
        self.text.setGeometry(QtCore.QRect(490, 410, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.text.setFont(font)
        self.text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text.setText("")
        self.text.setObjectName("text")
        self.camera_here_text = QtWidgets.QLabel(Dialog)
        self.camera_here_text.setGeometry(QtCore.QRect(20, 80, 361, 25))
        self.camera_here_text.setObjectName("camera_here_text")
        self.Threshold_here_text = QtWidgets.QLabel(Dialog)
        self.Threshold_here_text.setGeometry(QtCore.QRect(490, 80, 361, 25))
        self.Threshold_here_text.setObjectName("Threshold_here_text")
        self.toggle_text = QtWidgets.QLabel(Dialog)
        self.toggle_text.setGeometry(QtCore.QRect(490, 390, 361, 25))
        self.toggle_text.setObjectName("toggle_text")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 30, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.start_button.raise_()
        self.stop_button.raise_()
        self.threshhold_display.raise_()
        self.camera_display.raise_()
        self.color2_value.raise_()
        self.text.raise_()
        self.camera_here_text.raise_()
        self.Threshold_here_text.raise_()
        self.toggle_text.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start_button.setText(_translate("Dialog", "Start Webcam"))
        self.stop_button.setText(_translate("Dialog", "Stop Webcam"))
        self.color2_value.setText(_translate("Dialog", "Recognize Gesture:"))
        self.camera_here_text.setText(_translate("Dialog", "Camera Here:"))
        self.Threshold_here_text.setText(_translate("Dialog", "Threshold Here:"))
        self.toggle_text.setText(_translate("Dialog", "Text Here:"))
        self.label.setText(_translate("Dialog", "American Sign Language Recognition"))
